### PR TITLE
feat(Paginator): Adds Paginator

### PR DESCRIPTION
**Pull request by Bavfalcon9**
# PULL REQUEST

## **Overview**

This PR introduces Pagination Util (#47).
This PR is being actively edited, I will comment here when I am ready to merge.

## **Status**

- [ ] Typings have been updated or don't need to be.
- [ ] This PR have been tested and is ready to be merged.

## **Semantic versioning classification**

- [ ] This PR introduces *BREAKING* changes.
- [x] This PR adds new features, improve the code and implies minimal changes.
- [ ] This PR fixes a bug and references the relevant issue or documentation.
- [ ] This PR improves performance or code refactor without API changes.
- [ ] This PR **only** includes non-code changes (documentation, CI, tools...).

### CODE REVIEW

**Comment by Olybear9** [comment]
I made this PR so @Khaazz can modify how I'm going about this.

**Comment by Khaazz** [comment]
Quick sum up about what this is supposed to introduce in term of feature:
Paginator:
- takes a list of embed or pages
- sends back correct page regarding input:
  - number via awaitMessage / messageCollector
  - reaction via awaitReaction / reactionCollector
  - directly via input (`command #` return the page for #)

As I see it, we will need various structure:
- chunker that directly handle the data to output
- renderer that display the data needed like we want
- navigator that will take user input and call the rendered to correctly render the data

What could possibly be done:
- have only one instance of Paginator in the command, that loads and display static (via embed/text). EG: menu, always display the same data
- Have potentially a default view (embed or text) that takes dynamically data in param and renders it on user input
- directly use a function in the paginator that will return the data that needs to be displayed (eg: DB call)
- build dynamically embeds each time and renders it

- reactionCollector or messageCollector needs to potentially be given in parameter (to use global one / prevent spawning unecessary new listeners)

**Comment by Khaazz** [comment]
As I see it, you here have the basic chunker structure.
If you want me to review it more in depth, I'd need use case of the structure / examples / explanation of the architecture.

If anything in the above is not clear, make sure to tell me here or in discord. I am not sure myself on how / what it needs to do exactly, but I think I wrote above the basis of what it can do. I'll be able to judge better when you've done / explained more if the API you are working on seem sufficient to what I expect for this helper. 
Sidenote: I'll report the comment above in the original issue to keep track

**Comment by Khaaz** [comment]
Closing this due to inactivity. This is still a thing that needs to be done, and some implementation details are specified here.

**Pull request closed without merging**
